name: CI
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
          deno-version: 1.1.1
      - run: deno test -A --unstable
